HospitalManagmentApp/Controllers/DepartmentController.cs
using HospitalManagment.ViewModels.Department;
using HospitalManagmentApp.Data;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles ="Manager, Admin, Nurse, Doctor")]
    public class DepartmentController : Controller
    {
        
        private readonly IDepartmentService departmentService;

        public DepartmentController(IDepartmentService department)
        {
           
            this.departmentService = department;
        }
        public async Task<IActionResult> Index()
        {
            var dep = await departmentService.GetAllDepartmentsAsync();
            return View(dep);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var doctor = new AddDepartmentViewModel();           
            return View(doctor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddDepartmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
              
                return View(model);
            }

            var deparmentIsAdded = await departmentService.AddDepartmentAsync(model);

            if (deparmentIsAdded == false)
            {
                return View(model);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var department = await departmentService.GetEditDepartmentViewModelAsync(id);

            if (department == null)
            {
                return this.View();
            }

           
            return View(department);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditDepartmentViewModel model, Guid id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var isDepartmentUpdated = await departmentService.UpdateDepartmentAsync(id, model);

            if (isDepartmentUpdated == false)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var department = await departmentService.GetDeleteDepartmentViewModelAsync(id);

            if (department == null)
            {
                return BadRequest();
            }            

            return View(department);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteDepartmentViewModel model, Guid id)
        {
            var dep = await departmentService.DeleteDepartmentAsync(id);

            if (dep == null)
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Index));
        }

      
    }
}

HospitalManagmentApp/Controllers/DoctorController.cs
using HospitalManagment.ViewModels.Doctor;
using HospitalManagmentApp.DataModels;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles = "Manager,Admin")]
    public class DoctorController : Controller
    {
       
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDoctorService doctorService;
        public DoctorController(UserManager<ApplicationUser> userManager, IDoctorService doctorService)
        {
           
            this.userManager = userManager;
            this.doctorService = doctorService;
        }
        public async Task< IActionResult> Index(string? search, string? specialty, string? department)
        {
           IEnumerable<DoctorIndexViewModel> doctors= await this.doctorService.IndexGetAllDoctorsAsync(search,specialty,department);

            ViewData["SearchQuery"]=search;
            ViewData["Sepecialty"] = specialty;
            ViewData["Department"]= department;

            if (!doctors.Any())
            {
                ViewBag.Message = "No doctors available.";
                doctors= await this.doctorService.IndexGetAllDoctorsAsync(null, null, null);
            }

            return View(doctors);
        }

        
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var doctor = await doctorService.GetAddDoctorViewModel();
            return View(doctor);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddDoctorViewModel model)
        {
            if (!ModelState.IsValid) 
            {                 
                return View(model);
            }

           await this.doctorService.AddDoctorAsync(model);
            return RedirectToAction(nameof(Index));
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            EditDoctorViewModel? model=null;
            model = await doctorService.GetEditDoctorViewModel(id);           

            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditDoctorViewModel model,Guid id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            bool doctorIsUpdated= await this.doctorService
                .EditDoctorAsync(model);

            if (!doctorIsUpdated)
            {
                ModelState.AddModelError(string.Empty, "Error occured while updating doctor!");
                return this.View(model);
            }

            return RedirectToAction(nameof(Index));

        }

       
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var model= await this.doctorService.GetDeleteDoctorViewModel(id);
            return View(model);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteDoctorViewModel model, Guid id)
        {
            var doctorIsDeleted = await doctorService.DeleteDoctorAsync(model,id);

            if (doctorIsDeleted == false)
            {
                return BadRequest();
            }
                        
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AddDoctorToDepartment(Guid depId) 
        {
            var model=  await doctorService.GetAddDoctorToDepartmentViewModel(depId);

            if (model == null)
            {
                return BadRequest();
            }
            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> AddDoctorToDepartment(AddDoctorToDepartmentViewModel model,Guid depId)
        {
            var success = await doctorService.GetAddDoctorToDepartmentAsync(model, depId);

            if (!success)
            {
                return BadRequest("Failed to add the doctor to the department.");
            }

            return RedirectToAction("Index", "Department");
            
        }

        
    }
}

HospitalManagmentApp/Controllers/NurseController.cs
using HospitalManagment.ViewModels.Nurse;
using HospitalManagmentApp.Data;
using HospitalManagmentApp.DataModels;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using static HospitalManagmentApp.Common.EntityValidationConstants;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles = "Manager,Admin")]
    public class NurseController : Controller
    {
     
        private readonly UserManager<ApplicationUser> userManager;
        private readonly INurseService nurseService;

        public NurseController( UserManager<ApplicationUser> userManager,INurseService nurseService)
        {          
            this.userManager = userManager;
            this.nurseService = nurseService;
        }
        public async Task< IActionResult> Index(string? search, string? department)
        {
            var nurses=await nurseService.GetAllNursesAsync( search, department);
            ViewData["SearchQuery"] = search;            
            ViewData["Department"] = department;

            if (!nurses.Any())
            {
                ViewBag.Message = "No nurses available.";
                nurses= await nurseService.GetAllNursesAsync(search, department);
            }
            return View(nurses);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var nurse = await nurseService.GetAddNurseViewModelAsync();
           
            return View(nurse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddNurseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                
                return View(model);
            }

            await nurseService.AddNurseAsync(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var nurse = await nurseService.GetEditNurseViewModelAsync(id);

            if (nurse == null)
            {
                return this.View();
            }
                       

            return View(nurse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditNurseViewModel model, Guid id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var nurse = await nurseService.UpdateNurseAsync(id,model);
            if (nurse == false)
            {
                return BadRequest();
            }

           
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var nurse = await nurseService.GetDeleteNurseViewModelAsync(id);

            if (nurse == null)
            {
                return BadRequest();
            }


            return View(nurse);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteNurseViewModel model, Guid id)
        {
            var nurse = await nurseService.DeleteNurseAsync(id);

            if (nurse == false)
            {
                return BadRequest();
            }

            
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AddNurseToDepartment(Guid depId)
        {
            
            var nurse = await nurseService.GetAddNurseToDepartmentViewModelAsync(depId);

           if(nurse == null)
            {
                return BadRequest();
            }

            return View(nurse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNurseToDepartment(AddNurseToDepartmentViewModel model, Guid depId)
        {


            var nurse = await nurseService.AddNurseToDepartmentAsync(depId, model.SelectedNurseId);

            if (nurse == false)
            {
                return BadRequest();
            }

            return RedirectToAction("Index", "Department");
        }


    }
}

HospitalManagmentApp/Controllers/RoomController.cs
using HospitalManagment.ViewModels.Room;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles ="Manager, Nurse, Doctor, Admin")]
    public class RoomController : Controller
    {
        private IRoomService roomService;
        public RoomController(IRoomService room)
        {
            this.roomService = room;
        }
        public async Task<IActionResult> Index()
        {
            var rooms = await roomService.GetAllRoomsAsync();

            return View(rooms);

        }
     
        [HttpGet]
        public async Task<IActionResult> Add(Guid depId)
        {
            var room = await roomService.GetAddRoomViewModelAsync(depId);

            if(room == null)
            {
                return BadRequest();
            }
            
            return View(room);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddRoomViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var success = await roomService.AddRoomAsync(model);
            if (!success)
            {
                ModelState.AddModelError(string.Empty, "This room already exists in the current department.");
                return View(model);
            }

            return RedirectToAction("Index", "Department");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var model = await roomService.GetEditRoomViewModelAsync(id);
            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditRoomViewModel model, Guid id)
        {
            if (!ModelState.IsValid)
            {

                return View(model);
            }

            var roomIsUpdated = await roomService.UpdateRoomAsync(id, model);

            if (roomIsUpdated == false)
            {
                ModelState.AddModelError(string.Empty, "No such room exists in the current department.");
                return View(model);
              
            }                       

            
            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var room = await roomService.GetDeleteRoomViewModelAsync(id);

            if (room == null)
            {
                return BadRequest();
            }

            return View(room);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteRoomViewModel model, Guid id)
        {
            var success = await roomService.DeleteRoomAsync(id);
            if (!success)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

              

        private static string HasFreeBeds(bool hasFreeBeds)
        {
            if (hasFreeBeds)
            {
                return "Yes!";
            }
            return "No";
        }

    
    }
}

HospitalManagmentApp/Views/Department/Add.cshtml
@using HospitalManagment.ViewModels.Department
@model AddDepartmentViewModel

@{
    ViewData["Title"] = "Add New Department";
}

<div class="container mt-5">
    <h2 class="text-center">Add New Department</h2>

    <form asp-action="Add" method="post" class="mt-4">
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label asp-for="Name" class="control-label" p style="font-weight: bold;">Name of department</label>
            <input asp-for="Name" class="form-control" aria-required="true" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

       
        <button type="submit" class="btn btn-primary mt-3">Add Department</button>
        <a asp-action="Index" class="btn btn-secondary mt-3 ml-2">Cancel</a>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HospitalManagmentApp/Views/Department/Delete.cshtml
@using HospitalManagment.ViewModels.Department
@model DeleteDepartmentViewModel

@{
    ViewData["Title"] = "Delete Department";
}

<div class="container mt-5">
    <h2 class="text-center text-danger">Delete Department</h2>

    <p class="mt-4">Are you sure you want to delete @Model.Name department?</p>

    <div class="card p-3 mb-4">
        <h4>@Model.Name</h4>
       
    </div>

    <form asp-action="Delete" method="post">
        @Html.AntiForgeryToken()
        <input type="hidden" asp-for="DepartmentId" />

        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a asp-controller="Doctor" asp-action="Manage" class="btn btn-secondary ml-2">Cancel</a>
    </form>
</div>

HospitalManagmentApp/Views/Department/Edit.cshtml
@using HospitalManagment.ViewModels.Department
@model EditDepartmentViewModel
@{
    ViewData["Title"] = "Edit Department";
}

<div class="container mt-5">
    <h2 class="text-center">Edit Department</h2>

    <form asp-action="Edit" method="post" class="mt-4">
        @Html.AntiForgeryToken()
        <input type="hidden" asp-for="DepartmentId" />

        <div class="form-group">
            <label asp-for="Name" class="control-label">Department Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

       
        <input type="hidden" asp-for="@Model.DepartmentId" />
        <div class="mb-2">
            <input class="btn btn-warning btn-dark-text w-100 py-2 fw-bold rounded" type="submit" value="Save Changes" />
        </div>
        <div class="mb-2">
            <a asp-action="Manage" class="btn btn-secondary mt-3 ml-2">Cancel</a>
        </div>

        @*   <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
        <a asp-action="Manage" class="btn btn-secondary mt-3 ml-2">Cancel</a> *@
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HospitalManagmentApp/Views/Department/Index.cshtml
<style>
   
</style>

<head>
    <link rel="stylesheet" href="~/css/departmentIndex.css" />
</head>

<h2>All Departments in the Hospital</h2>

<div class="row">
    @foreach (var department in Model)

    {
        <div class="col-md-6">
            <!-- Larger department cards -->
            <div class="card mb-4 shadow-sm">
                <img src="~/images/Department.jpg" class="card-img-top" alt="Department Image" style="height: 250px; object-fit: cover;">
                <div class="card-body">
                    <p class="card-title">Department name: @department.Name</p>
                    <p class="card-text">Doctors: @department.DepartmentDoctors</p>
                    <p class="card-text">Nurses: @department.Nurses</p>
                    <p class="card-text">Rooms: @department.Rooms</p>
                    <div class="btn-group" role="group" aria-label="Department Actions">

                        <!-- Add Doctor -->
                        <form asp-controller="Doctor" asp-action="AddDoctorToDepartment" method="get" class="d-inline">
                            <input type="hidden" name="depId" value="@department.Id" />
                            <button type="submit" class="btn btn-add">Add Doctor</button>
                        </form>

                        <!-- Add Nurse -->
                        <form asp-controller="Nurse" asp-action="AddNurseToDepartment" method="get" class="d-inline">
                            <input type="hidden" name="depId" value="@department.Id" />
                            <button type="submit" class="btn btn-add">Add Nurse</button>
                        </form>

                        <!-- Add Room -->
                        <form asp-controller="Room" asp-action="Add" method="get" class="d-inline">
                            <input type="hidden" name="depId" value="@department.Id" />
                            <button type="submit" class="btn btn-add">Add Room</button>
                        </form>

                        <!-- Update Button -->
                        <a asp-controller="Department" asp-action="Edit" asp-route-id="@department.Id" class="btn btn-update">Update</a>

                        <!-- Delete Button -->
                        <form asp-controller="Department" asp-action="Delete" asp-route-id="@department.Id" method="post" class="d-inline">
                            <button type="submit" class="btn btn-delete" onclick="return confirm('Are you sure you want to delete this department?');">
                                Delete
                            </button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    }
</div>