HospitalManagmentApp/Controllers/PatientController.cs
using HospitalManagment.ViewModels.Patient;
using HospitalManagmentApp.DataModels;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using System.Drawing.Printing;
using static HospitalManagmentApp.Common.EntityValidationConstants;
using AuthorizeAttribute = Microsoft.AspNetCore.Authorization.AuthorizeAttribute;


using Controller = Microsoft.AspNetCore.Mvc.Controller;
using HttpGetAttribute = Microsoft.AspNetCore.Mvc.HttpGetAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles ="Doctor, Nurse, Manager,Admin")]
    public class PatientController : Controller
    {
        private readonly UserManager <ApplicationUser> userManager;
        private readonly IPatientService patientService;

        public PatientController(UserManager<ApplicationUser> userManager, IPatientService patientService)
        {
            this.userManager = userManager;
            this.patientService = patientService;
        }
        public async Task<IActionResult> Index(string? search, string? department, int? room, int pageNumber = 1, int pageSize = 3)   
        {
            var totalPatients = await patientService.GetTotalPatientsCountAsync(search, department, room);
            var totalPages = (int)Math.Ceiling((double)totalPatients / pageSize);

            // all patients for the current page
            var patients = await patientService.GetAllPatientsAsync(search, department, room, pageSize, pageNumber);

            // add info for pagination and filters
            ViewData["SearchQuery"] = search;
            ViewData["Department"] = department;
            ViewData["Room"] = room;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;

            if (!patients.Any())
            {
                ViewBag.Message = "No patients available for the searched criteria. Displaying all patients below.";
                patients = await patientService.GetAllPatientsAsync(null, null, null, pageSize, pageNumber);
            }

            return View(patients);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var patient = await patientService.PrepareAddPatientViewModelAsync() ;
            
            return View(patient);
        }

        [HttpGet]
        public async Task<IActionResult> GetFreeRooms(Guid departmentId)
        {
            var freeRooms = await patientService.GetFreeRoomsAsync(departmentId);

            return Json(freeRooms);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddPatientViewModel model)
        {
            if (!ModelState.IsValid)
            {
               AddPatientViewModel addPatientViewModel =await patientService.PrepareAddPatientViewModelAsync();

                return View(addPatientViewModel);
            }

            var isPatientAdded=await patientService.AddPatientAsync(model);
            if (!isPatientAdded)
            {
                return View(model);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Manage()
        {
            var patients = await patientService.Menage();

            return View(patients);
        }

        [HttpGet]
        public async Task<IActionResult> MovePatient(Guid id)
        {
            var patient=await patientService.GetMovePatientModelAsync(id);

            if (patient == null)
            {
                return BadRequest();
            }

            return View(patient);
        }

        [HttpGet]
        public async Task<IActionResult> GetFreeRoomsOnMove(Guid departmentId)
        {
            var freeRooms = await patientService.GetFreeRoomsOnMoveAsync(departmentId);

            return Json(freeRooms);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MovePatient(MovePatientToDepartmentViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var patientIsMoved = await patientService.MovePatientAsync(model);

            if (patientIsMoved == false)
                {
                return BadRequest(); 
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> DischargePatient(Guid id)
        {
            var patient = await patientService.GetDischargePatientViewModel(id);

            if (patient == null)
            {
                return BadRequest();
            }
            //TODO: check if user is in this department!!


            return View(patient);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DischargePatient(DischargePatientViewModel model, Guid id)
        {
            var patientIsDischarged = await patientService.DischargePatientAsync(model,id);

            if (patientIsDischarged == false)
            {
                return BadRequest();
            }
                       
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> SeePatientMedicalInfo(Guid patientId)
        {
            var patientMedicalInfo=await patientService.SeePatientMedicalInfo(patientId);

            if (patientMedicalInfo == null)
            {
                return NotFound();
            }
            return View(patientMedicalInfo);
        }

        [HttpGet]
        [Route("Patient/AddTreatmentToPatient")]
        public async Task<IActionResult> AddTreatmentToPatient(Guid patientId)
        {
           
            var patient = await patientService.GetAddTreatmentToPatientViewModel(patientId);

            if (patient == null)
            {
                return NotFound("Patient not found.");
            }

            return View(patient);
        }

        [HttpPost]
        [Route("Patient/AddTreatmentToPatientAsync")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTreatmentToPatientAsync(AddTreatmentToPatientViewModel model)
        {
            
            if (!ModelState.IsValid)
            {               
                return View( model);
            }

            // Save changes to the database
           var result = await patientService.AddTreatmentToPatientAsync(model);
            if (result == true)
            {
                TempData["SuccessMessage"] = "Treatment was successfully added to the patient.";

                // Redirect to the Index action
                return RedirectToAction("Index");
                //return RedirectToAction(nameof(AddTreatmentToPatient),new { patientId=model.PatientId});
            }

            else
            {
                ModelState.AddModelError("", "Failed to add treatment.");
                return View(model);
            }

            
        }

        [HttpGet]
        public async Task<IActionResult> ChangeTreatments(Guid patientId)
        {
           var model=await patientService.GetChangeTreatmentViewModel(patientId);

            if (model == null)
            {
                return NotFound("Patient not found.");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeTreatments(ChangeTreatmentsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model); 
            }

            var result= await patientService.ChangeTreatmentsAsync(model);
            if (result == true)
            {

                TempData["SuccessMessage"] = "Treatments updated successfully.";
                return RedirectToAction("Index");
            }

            else
            {
               
                TempData["ErrorMessage"] = "Failed to update treatments. Please try again.";
                return RedirectToAction("ChangeTreatments", new { patientId = model.PatientId });
            }
        }
    }
}

HospitalManagmentApp/Views/Patient/Add.cshtml
@using HospitalManagment.ViewModels.Patient
@using System.Security.Claims
@model AddPatientViewModel

<div class="container mt-5">
    <h2 class="text-center">Add New Patient</h2>

    <form asp-action="Add" method="post" class="mt-4">
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label asp-for="FirstName" class="control-label" style="font-weight: bold;">First Name</label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        
        <div class="form-group">
            <label asp-for="LastName" class="control-label" style="font-weight: bold;">Last Name</label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

      
        <div class="form-group">
            <label asp-for="EGN" class="control-label" style="font-weight: bold;">EGN of Patient</label>
            <input asp-for="EGN" class="form-control" />
            <span asp-validation-for="EGN" class="text-danger"></span>
        </div>

    
        <div class="form-group">
            <label asp-for="Address" class="control-label" style="font-weight: bold;">Address</label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

      
        <div class="form-group">
            <label asp-for="EmailAddress" class="control-label" style="font-weight: bold;">Email</label>
            <input asp-for="EmailAddress" type="email" class="form-control" />
            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Password" class="control-label" style="font-weight: bold;">Password</label>
            <input asp-for="Password" type="password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

       
        <div class="form-group">
            <label asp-for="PhoneNumber" class="control-label" style="font-weight: bold;">Phone Number</label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="HasMedicalInsurance" class="control-label" style="font-weight: bold;">Has Medical Insurance?</label>
            <input asp-for="HasMedicalInsurance" type="checkbox" class="form-check-input" />
            <span asp-validation-for="HasMedicalInsurance" class="text-danger"></span>
        </div>

       
        <div class="form-group">
            <label asp-for="DepartmentId" class="control-label" style="font-weight: bold;">Department</label>
            <select asp-for="DepartmentId" class="form-control" id="departmentDropdown" asp-items="@(new SelectList(Model.Departments, "Id", "Name"))">
                <option value="">Select Department...</option>
            </select>
            <span asp-validation-for="DepartmentId" class="text-danger"></span>
        </div>

        
        <div class="form-group">
            <label asp-for="RoomId" class="control-label" style="font-weight: bold;">Room</label>
            <select asp-for="RoomId" class="form-control" id="roomDropdown">
                <option value="">-- Select a Room --</option>
            </select>
            <span asp-validation-for="RoomId" class="text-danger"></span>
        </div>

        @if(!User.IsInRole("Doctor")){
        <div class="form-group">
            <label for="SelectedDoctorId">Assign a Doctor</label>
            <select asp-for="SelectedDoctorId" class="form-control">
                <option value="">Select a Doctor</option>
                @foreach (var doctor in Model.Doctors)

                {
                    <option value="@doctor.Value">@doctor.Text</option>
                }
            </select>
        </div>
        }
        @if(User.IsInRole("Doctor"))
        {
          
            <input type="hidden" name="SelectedDoctorId" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)" />
        }
      
        <button type="submit" class="btn btn-primary mt-3">Add New Patient</button>
        <a asp-action="Index" class="btn btn-secondary mt-3 ml-2">Cancel</a>
    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#departmentDropdown').change(function () {
                var departmentId = $(this).val();
                var roomDropdown = $('#roomDropdown');

              
                roomDropdown.empty().append('<option value="">-- Select a Room --</option>');

                if (departmentId) {
                   
                    $.get('/Patient/GetFreeRooms', { departmentId: departmentId }, function (data) {
                        data.forEach(function (room) {
                            roomDropdown.append($('<option>', { value: room.value, text: room.text }));
                        });
                    }).fail(function () {
                        alert('Error fetching free rooms. Please try again.');
                    });
                }
            });
        });
    </script>
}

HospitalManagmentApp/Views/Patient/AddTreatmentToPatient.cshtml
@using HospitalManagment.ViewModels.Patient
@model AddTreatmentToPatientViewModel

@{
    ViewData["Title"] = "Assign Treatments to Patient";
}

<div class="container mt-5">
    <h2 class="text-center">Assign Treatments to Patient</h2>
    <hr />

   
    <div class="card my-4">
        <div class="card-body">
            <h4 class="card-title">Patient Details</h4>
            <p><strong>First Name:</strong> @Model.FirstName</p>
            <p><strong>Last Name:</strong> @Model.LastName</p>
            <p><strong>Department:</strong> @Model.DepartmentName</p>
        </div>
    </div>

  
    <form asp-action="AddTreatmentToPatientAsync" asp-controller="Patient" method="post">
        @Html.AntiForgeryToken()
        
        <input type="hidden" asp-for="PatientId" />
        <input type="hidden" asp-for="DepartmentName" />
        <input type="hidden" asp-for="FirstName" />
        <input type="hidden" asp-for="LastName" />

        <div class="form-group">
            <label for="Treatments" style="font-weight: bold;">Available Treatments</label>
            <select asp-for="SelectedTreatmentIds" class="form-control" multiple size="10">
                @foreach (var treatment in Model.AvailableTreatments)
                {
                    <option value="@treatment.Value">@treatment.Text</option>
                }
            </select>

            <span class="form-text text-muted">Hold down the Ctrl (Windows) or Command (Mac) key to select multiple treatments.</span>
        </div>

        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a asp-action="Index" class="btn btn-secondary ml-2">Cancel</a>
        </div>
    </form>
</div>

HospitalManagmentApp/Views/Patient/ChangeTreatments.cshtml
@using HospitalManagment.ViewModels.Patient
@model ChangeTreatmentsViewModel

<h2>Change Treatments for @Model.FirstName @Model.LastName</h2>
<p>Department: @Model.DepartmentName</p>

<form asp-action="ChangeTreatments" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="PatientId" />
    <input type="hidden" asp-for="FirstName" />
    <input type="hidden" asp-for="LastName" />
    <input type="hidden" asp-for="DepartmentName" />

    <div class="form-group">
        <h4>Assigned Treatments</h4>
        @if (Model.AssignedTreatments.Any())

        {
            <select asp-for="RemovedTreatmentIds" class="form-control" multiple>
                @foreach (var treatment in Model.AssignedTreatments)

                {
                    <option value="@treatment.Value">@treatment.Text</option>
                }
            </select>
            <span class="form-text">Select treatments to remove.</span>
        }

        else

        {
            <p>No treatments assigned to this patient.</p>
        }
    </div>

    <div class="form-group">
        <h4>Available Treatments</h4>
        <select asp-for="NewTreatmentIds" class="form-control" multiple>
            @foreach (var treatment in Model.AvailableTreatments)
            {
                <option value="@treatment.Value">@treatment.Text</option>
            }
        </select>
        <span class="form-text">Select treatments to add.</span>
    </div>

    <div class="form-group mt-3">
        <button type="submit" class="btn btn-primary">Save Changes</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

HospitalManagmentApp/Views/Patient/DischargePatient.cshtml
@using HospitalManagment.ViewModels.Patient
@model DischargePatientViewModel

<div class="container mt-5">
    <h2 class="text-center">Discharge Patient</h2>

    <form asp-action="DischargePatient" method="post" class="mt-4">
        @Html.AntiForgeryToken()
        <input type="hidden" asp-for="Id" />

      
        <div class="form-group">
            <label asp-for="Name" class="control-label" style="font-weight: bold;">Patient Name</label>
            <input asp-for="Name" class="form-control" readonly />
        </div>

      
        <div class="form-group">
            <label asp-for="Id" class="control-label" style="font-weight: bold;">Patient ID</label>
            <input asp-for="Id" class="form-control" readonly />
        </div>

       
        <form asp-action="DischargePatient" method="post">
            <input type="hidden" asp-for="Id" />

            <button type="submit" class="btn btn-danger">Discharge patient?</button>
            <a asp-controller="Patient" asp-action="Manage" class="btn btn-secondary ml-2">Cancel</a>
        </form>
    
    </form>
</div>

HospitalManagmentApp/Views/Patient/Index.cshtml
@using HospitalManagment.ViewModels.Patient
@model IEnumerable<PatientIndexViewModel>

@{
    ViewData["Title"] = "All Patients";
}

@if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))

{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @ViewBag.SuccessMessage
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<h2>All Patients</h2>

<!-- Filter Form -->
<form asp-action="Index" method="get" class="mb-4">
    <div class="row">
        <div class="col">
            <input type="text"
                   name="search"
                   class="form-control"
                   placeholder="Search by Name..."
                   value="@ViewData["SearchQuery"]" />
        </div>
        <div class="col">
            <input type="text"
                   name="department"
                   class="form-control"
                   placeholder="Patient`s admission department..."
                   value="@ViewData["Department"]" />
        </div>
        <div class="col">
            <input type="number"
                   name="room"
                   class="form-control"
                   placeholder="Patient`s room"
                   value="@ViewData["Room"]" />
        </div>
        <div class="col">
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>
    </div>
</form>

<!-- Patient Cards -->
<div class="row">
    @if (Model.Any())

    {
        @foreach (var patient in Model)

        {
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img src="~/images/patient.png" class="card-img-top" alt="Patient Image" style="height: 200px; object-fit: cover;">
                    <div class="card-body">
                        <p class="card-title">Name: @patient.Name</p>
                        <p class="card-title">Address: @patient.Address</p>
                        <p class="card-title">Phone number: @patient.PhoneNumber</p>
                        <p class="card-title">Has medical insurance: @patient.HasMedicalInsurance</p>
                        <p class="card-title">Email: @patient.EmailAddress</p>
                        <p class="card-text">Department: @patient.Department</p>
                        <p class="card-text">Room Number: @patient.Room</p>

                        <div class="text-center mt-3">
                            <a asp-controller="Patient" asp-action="SeePatientMedicalInfo" asp-route-patientId="@patient.Id" class="btn btn-primary">
                                View Medical Info
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    }

    else

    {
        <div class="alert alert-warning" role="alert">
            No patients found for the given criteria.
        </div>
    }
</div>

<!-- Pagination Controls -->
@if (ViewBag.TotalPages > 1)

{
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            @for (int i = 1; i <= ViewBag.TotalPages; i++)

            {
                <li class="page-item @(ViewBag.CurrentPage == i ? "active" : "")">
                    <a class="page-link"
                       href="?pageNumber=@i&pageSize=3&searchQuery=@ViewData["SearchQuery"]&department=@ViewData["Department"]&room=@ViewData["Room"]">
                        @i
                    </a>
                </li>
            }
        </ul>
    </nav>
}

HospitalManagmentApp/Views/Patient/Manage.cshtml
@using HospitalManagment.ViewModels.Patient
@model IEnumerable<PatientIndexViewModel>

@{
    ViewData["Title"] = "All Patients";
}

<h2>All Patients</h2>

<div class="row">
    @foreach (var patient in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <img src="~/images/patient.png" class="card-img-top" alt="Doctor Image" style="height: 200px; object-fit: cover;">
                <div class="card-body">
                    <p class="card-title">Name: @patient.Name</p>
                    <p class="card-title">Address: @patient.Address</p>
                   
                    <p class="card-title">EGN: @patient.EGN</p>                   
                    <p class="card-text">Department: @patient.Department</p>
                    <p class="card-text">RoomNumber: @patient.Room</p>

                    <form asp-action="DischargePatient" method="get" class="d-inline">
                        <input type="hidden" name="id" value="@patient.Id" />
                        <button type="submit" class="btn btn-danger btn-sm">Discharge</button>
                    </form>

                   
                    <a asp-action="MovePatient" asp-route-id="@patient.Id" class="btn btn-primary btn-sm ml-2">
                        Move to Another Department
                    </a>
                </div>
            </div>
        </div>
    }
</div>

HospitalManagmentApp/Views/Patient/MovePatient.cshtml
@using HospitalManagment.ViewModels.Patient
@model MovePatientToDepartmentViewModel

<div class="container mt-5">
    <h2 class="text-center">Move Patient</h2>

    <form asp-action="MovePatient" method="post" class="mt-4">
        @Html.AntiForgeryToken()
        <input type="hidden" asp-for="PatientId" />

     
        <div class="form-group">
            <label asp-for="Name" class="control-label" style="font-weight: bold;">Patient Name</label>
            <input asp-for="Name" class="form-control" readonly />
        </div>

       
        <div class="form-group">
            <label asp-for="EGN" class="control-label" style="font-weight: bold;">Patient EGN</label>
            <input asp-for="EGN" class="form-control" readonly />
        </div>
        <div class="form-group">
            <label asp-for="CurrentDepartment" class="control-label" style="font-weight: bold;">Current Department</label>
            <input asp-for="CurrentDepartment" class="form-control" readonly />
        </div>

        <div class="form-group">
            <label asp-for="CurrentRoom" class="control-label" style="font-weight: bold;">Current room number</label>
            <input asp-for="CurrentRoom" class="form-control" readonly />
        </div>


      
        <div class="form-group">
            <label asp-for="NewDepartmentId" class="control-label" style="font-weight: bold;">Select Department</label>
            <select asp-for="NewDepartmentId" class="form-control" id="departmentDropdown" asp-items="@(new SelectList(Model.Departments, "Id", "Name"))">
                <option value="">Select Department...</option>                
            </select>
            <span asp-validation-for="NewDepartmentId" class="text-danger"></span>
        </div>

       
        <div class="form-group">
            <label asp-for="NewRoomId" class="control-label" style="font-weight: bold;">Select Room</label>
            <select asp-for="NewRoomId" class="form-control" id="roomDropdown">
                <option value="">-- Select a Room --</option>
            </select>
            <span asp-validation-for="NewRoomId" class="text-danger"></span>
        </div>

  
        <button type="submit" class="btn btn-primary mt-3">Move Patient</button>
        <a asp-action="Index" class="btn btn-secondary mt-3 ml-2">Cancel</a>
    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#departmentDropdown').change(function () {
                var departmentId = $(this).val();
                var roomDropdown = $('#roomDropdown');

              
                roomDropdown.empty().append('<option value="">-- Select a Room --</option>');

                if (departmentId) {
                  
                    $.get('/Patient/GetFreeRoomsOnMove', { departmentId: departmentId }, function (data) {
                        data.forEach(function (room) {
                            roomDropdown.append($('<option>', { value: room.value, text: room.text }));
                        });
                    }).fail(function () {
                        alert('Error fetching rooms. Please try again.');
                    });
                }
            });
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.13/jquery.validate.unobtrusive.min.js"></script>
}

HospitalManagmentApp/Views/Patient/SeePatientMedicalInfo.cshtml
@using HospitalManagment.ViewModels.Patient;
@model PatientMedicalInfoViewModel

@{
    ViewData["Title"] = "Patient Medical Information";
}

<div class="container mt-5">
    <h2 class="text-center">Patient Medical Information</h2>
    <hr />


    <div class="card my-4">
        <div class="card-body">
            <h4 class="card-title">Basic Information</h4>
            <p><strong>First Name:</strong> @Model.FirstName</p>
            <p><strong>Last Name:</strong> @Model.LastName</p>
            <p><strong>Department:</strong> @Model.DepartmentName</p>
           
        </div>
    </div>

 
    <div class="card my-4">
        <div class="card-body">
            <h4 class="card-title">Treatments</h4>
            @if (Model.Treatments != null && Model.Treatments.Any())
            {
                <ul class="list-group">
                    @foreach (var treatment in Model.Treatments)
                    {
                        <li class="list-group-item">@treatment</li>
                    }
                </ul>
            }
            else
            {
                <p>No treatments available.</p>
            }
        </div>
    </div>

 
    @if (User.IsInRole("Doctor") || User.IsInRole("Nurse"))

    {
        <div class="text-center mt-4">
            <a asp-controller="Patient" asp-action="AddTreatmentToPatient" asp-route-patientId="@Model.PatientId" class="btn btn-primary">
                Add Treatments to patients
            </a>
        </div>
        <div class="text-center mt-4">
            <a asp-controller="Patient" asp-action="ChangeTreatments" asp-route-patientId="@Model.PatientId" class="btn btn-primary">
                Change Treatments
            </a>
        </div>
    }
</div>