HospitalManagmentApp/Controllers/DoctorController.cs
using HospitalManagment.ViewModels.Doctor;
using HospitalManagmentApp.DataModels;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles = "Manager,Admin")]
    public class DoctorController : Controller
    {
       
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDoctorService doctorService;
        public DoctorController(UserManager<ApplicationUser> userManager, IDoctorService doctorService)
        {
           
            this.userManager = userManager;
            this.doctorService = doctorService;
        }
        public async Task< IActionResult> Index(string? search, string? specialty, string? department)
        {
           IEnumerable<DoctorIndexViewModel> doctors= await this.doctorService.IndexGetAllDoctorsAsync(search,specialty,department);

            ViewData["SearchQuery"]=search;
            ViewData["Sepecialty"] = specialty;
            ViewData["Department"]= department;

            if (!doctors.Any())
            {
                ViewBag.Message = "No doctors available.";
                doctors= await this.doctorService.IndexGetAllDoctorsAsync(null, null, null);
            }

            return View(doctors);
        }

        
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var doctor = await doctorService.GetAddDoctorViewModel();
            return View(doctor);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddDoctorViewModel model)
        {
            if (!ModelState.IsValid) 
            {                 
                return View(model);
            }

           await this.doctorService.AddDoctorAsync(model);
            return RedirectToAction(nameof(Index));
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            EditDoctorViewModel? model=null;
            model = await doctorService.GetEditDoctorViewModel(id);           

            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditDoctorViewModel model,Guid id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            bool doctorIsUpdated= await this.doctorService
                .EditDoctorAsync(model);

            if (!doctorIsUpdated)
            {
                ModelState.AddModelError(string.Empty, "Error occured while updating doctor!");
                return this.View(model);
            }

            return RedirectToAction(nameof(Index));

        }

       
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var model= await this.doctorService.GetDeleteDoctorViewModel(id);
            return View(model);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteDoctorViewModel model, Guid id)
        {
            var doctorIsDeleted = await doctorService.DeleteDoctorAsync(model,id);

            if (doctorIsDeleted == false)
            {
                return BadRequest();
            }
                        
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> AddDoctorToDepartment(Guid depId) 
        {
            var model=  await doctorService.GetAddDoctorToDepartmentViewModel(depId);

            if (model == null)
            {
                return BadRequest();
            }
            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> AddDoctorToDepartment(AddDoctorToDepartmentViewModel model,Guid depId)
        {
            var success = await doctorService.GetAddDoctorToDepartmentAsync(model, depId);

            if (!success)
            {
                return BadRequest("Failed to add the doctor to the department.");
            }

            return RedirectToAction("Index", "Department");
            
        }

        
    }
}

HospitalManagmentApp/Controllers/TreatmentController.cs
using HospitalManagment.ViewModels.Treatment;
using HospitalManagmentApp.Services.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using AuthorizeAttribute = Microsoft.AspNetCore.Authorization.AuthorizeAttribute;
using HttpGetAttribute = Microsoft.AspNetCore.Mvc.HttpGetAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;

namespace HospitalManagmentApp.Controllers
{
    [Authorize(Roles ="Doctor,Nurse, Admin,Manager")]
    public class TreatmentController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly ITreatmentService treatmentService;
        public TreatmentController( ITreatmentService treatmentService)
        {
            this.treatmentService = treatmentService;

        }
        public async Task<IActionResult> Index()
        {
            var treatments= await treatmentService.GetAllTreatmentsAsync();
            return View(treatments);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var treatment = new AddTreatmentViewModel();            
            return View(treatment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddTreatmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
               
                return View(model);
            }

            var treatment = await treatmentService.AddTreatmentAsync(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var treatment = await treatmentService.GetEditTreatmentViewModelAsync(id);

            return View(treatment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditTreatmentViewModel model, Guid id)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var treatment = await treatmentService.UpdateTreatmentAsync(id, model);

            if (treatment == null)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var treatment = await treatmentService.GetDeleteTreatmentViewModelAsync(id);

            if (treatment == null)
            {
                return BadRequest();
            }
                        
            return View(treatment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(DeleteTreatmentViewModel model, Guid id)
        {
            var treatment = await treatmentService.DeleteTreatmentAsync(id);

            if (treatment == null)
            {
                return BadRequest();
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

HospitalManagmentApp/Views/Treatment/Add.cshtml
@using HospitalManagment.ViewModels.Treatment
@model AddTreatmentViewModel

@{
    ViewData["Title"] = "Add New Treatment";
}

<div class="container mt-5">
    <h2 class="text-center">Add New Treatment</h2>

    <form asp-action="Add" method="post" class="mt-4">
        <div class="form-group">
            <label asp-for="Name" class="control-label" p style="font-weight: bold;">Name of treatment</label>
            <input asp-for="Name" class="form-control" aria-required="true" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="control-label" p style="font-weight: bold;">Price of treatment</label>
            <input asp-for="Price" class="form-control" aria-required="true" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary mt-3">Add Treatment</button>
        <a asp-action="Index" class="btn btn-secondary mt-3 ml-2">Cancel</a>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HospitalManagmentApp/Views/Treatment/Delete.cshtml
@using HospitalManagment.ViewModels.Treatment
@model DeleteTreatmentViewModel

@{
    ViewData["Title"] = "Delete Treatment";
}

<div class="container mt-5">
    <h2 class="text-center text-danger">Delete Treatment @Model.Name</h2>

    <p class="mt-4">Are you sure you want to delete @Model.Name treatment?</p>

    <div class="card p-3 mb-4">
        <h4>@Model.Name</h4>

    </div>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="TreatmentId" />

        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a asp-controller="Doctor" asp-action="Manage" class="btn btn-secondary ml-2">Cancel</a>
    </form>
</div>

HospitalManagmentApp/Views/Treatment/Edit.cshtml
@using HospitalManagment.ViewModels.Treatment
@model EditTreatmentViewModel
@{
    ViewData["Title"] = "Edit treatment ";
}

<div class="container mt-5">
    <h2 class="text-center">Edit treatment @Model.Name</h2>

    <form asp-action="Edit" method="post" class="mt-4">
        <input type="hidden" asp-for="TreatmentId" />

        <div class="form-group">
            <label asp-for="Name" class="control-label">Treatment Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="control-label">Treatment price</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>


        <input type="hidden" asp-for="@Model.TreatmentId" />
        <div class="mb-2">
            <input class="btn btn-warning btn-dark-text w-100 py-2 fw-bold rounded" type="submit" value="Save Changes" />
        </div>
        <div class="mb-2">
            <a asp-action="Manage" class="btn btn-secondary mt-3 ml-2">Cancel</a>
        </div>

       
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HospitalManagmentApp/Views/Treatment/Index.cshtml
@using HospitalManagment.ViewModels.Treatment
@model IEnumerable<TreatmentIndexViewModel>

@{
    ViewData["Title"] = "All Treatment";
}

<h2>All Treatments </h2>

<div class="row">
    @foreach (var treatment in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <img src="~/images/treatment.png" class="card-img-top" alt="Doctor Image" style="height: 200px; object-fit: cover;">
                <div class="card-body">
                    <p class="card-title"><strong>Treatment name: </strong>@treatment.Name</p>
                    <p class="card-text"><strong>Treatment ptice: </strong>@treatment.Price</p>
                   
                    <div class="btn-group" role="group" aria-label="Treatment Actions">

                        
                        <!-- Update Button -->
                        <a asp-controller="Treatment" asp-action="Edit" asp-route-id="@treatment.Id" class="btn btn-warning btn-sm">Update</a>

                        <!-- Delete Button -->
                        <form asp-controller="Treatment" asp-action="Delete" asp-route-id="@treatment.Id" method="post" class="d-inline">
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this doctor?');">
                                Delete
                            </button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    }
</div>